services:
  - type: web
    name: sistema-backend-gestao-fitpro
    env: node
    plan: free
    buildCommand: yarn --frozen-lockfile install && yarn prisma generate && yarn seed && yarn build && yarn db:migrate:deploy
    startCommand: NODE_OPTIONS=--use-system-ca yarn start:prod
    autoDeploy: true
